name: HDepService

on:
  push:
    branches: [ main ]

jobs:
  heroku-deploy-1:
    name: Deploy HS1 (always online 1-16)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 1 (always online 1-16)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_1 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_1 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_1 }}

  heroku-deploy-2:
    name: Deploy HS2 (always online 1-16)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 2 (always online 1-16)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_2 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_2 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_2 }}

  heroku-deploy-3:
    name: Deploy HS3 (always online 17-31)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 3 (always online 17-31)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_3 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_3 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_3 }}

  heroku-deploy-4:
    name: Deploy HS4 (always online 17-31)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 4 (always online 17-31)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_4 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_4 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_4 }}
  
  heroku-deploy-5:
    name: Deploy HS5 (fallback)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 5 (fallback)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_5 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_5 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_5 }}

  heroku-deploy-6:
    name: Deploy HS6 (fallback)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 6 (fallback)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_6 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_6 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_6 }}

  heroku-deploy-7:
    name: Deploy HS7 (fallback)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 7 (fallback)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_7 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_7 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_7 }}

  heroku-deploy-8:
    name: Deploy HS8 (fallback)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to Heroku - Service 8 (fallback)
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY_8 }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_8 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_8 }}